
from ..config import *

construct_000000 = ConstructorConfig(exposed=FlagExposed.kNo, constructor=FlagConstructor.kDontAll, length=0, v8_array=0, immutable=0, has_constructor=0)
construct_000001 = ConstructorConfig(exposed=FlagExposed.kNo, constructor=FlagConstructor.kDontAll, length=0, v8_array=0, immutable=0, has_constructor=1)
construct_000020 = ConstructorConfig(exposed=FlagExposed.kNo, constructor=FlagConstructor.kDontAll, length=0, v8_array=0, immutable=FlagImmutable.prototype, has_constructor=0)
construct_000031 = ConstructorConfig(exposed=FlagExposed.kNo, constructor=FlagConstructor.kDontAll, length=0, v8_array=0, immutable=FlagImmutable.instance | FlagImmutable.prototype, has_constructor=1)
construct_000100 = ConstructorConfig(exposed=FlagExposed.kNo, constructor=FlagConstructor.kDontAll, length=0, v8_array=FlagArrayProto.iterator, immutable=0, has_constructor=0)
construct_000101 = ConstructorConfig(exposed=FlagExposed.kNo, constructor=FlagConstructor.kDontAll, length=0, v8_array=FlagArrayProto.iterator, immutable=0, has_constructor=1)
construct_0003101 = ConstructorConfig(exposed=FlagExposed.kNo, constructor=FlagConstructor.kDontAll, length=0, v8_array=FlagArrayProto.iterator | FlagArrayProto.entries | FlagArrayProto.keys | FlagArrayProto.values | FlagArrayProto.forEach, immutable=0, has_constructor=1)
construct_010000 = ConstructorConfig(exposed=FlagExposed.kNo, constructor=FlagConstructor.kNew, length=0, v8_array=0, immutable=0, has_constructor=0)
construct_010001 = ConstructorConfig(exposed=FlagExposed.kNo, constructor=FlagConstructor.kNew, length=0, v8_array=0, immutable=0, has_constructor=1)
construct_010100 = ConstructorConfig(exposed=FlagExposed.kNo, constructor=FlagConstructor.kNew, length=0, v8_array=FlagArrayProto.iterator, immutable=0, has_constructor=0)
construct_011000 = ConstructorConfig(exposed=FlagExposed.kNo, constructor=FlagConstructor.kNew, length=1, v8_array=0, immutable=0, has_constructor=0)
construct_100001 = ConstructorConfig(exposed=FlagExposed.kYes, constructor=FlagConstructor.kDontAll, length=0, v8_array=0, immutable=0, has_constructor=1)
construct_100021 = ConstructorConfig(exposed=FlagExposed.kYes, constructor=FlagConstructor.kDontAll, length=0, v8_array=0, immutable=FlagImmutable.prototype, has_constructor=1)
construct_100031 = ConstructorConfig(exposed=FlagExposed.kYes, constructor=FlagConstructor.kDontAll, length=0, v8_array=0, immutable=FlagImmutable.instance | FlagImmutable.prototype, has_constructor=1)
construct_100101 = ConstructorConfig(exposed=FlagExposed.kYes, constructor=FlagConstructor.kDontAll, length=0, v8_array=FlagArrayProto.iterator, immutable=0, has_constructor=1)
construct_1003101 = ConstructorConfig(exposed=FlagExposed.kYes, constructor=FlagConstructor.kDontAll, length=0, v8_array=FlagArrayProto.iterator | FlagArrayProto.entries | FlagArrayProto.keys | FlagArrayProto.values | FlagArrayProto.forEach, immutable=0, has_constructor=1)
construct_110001 = ConstructorConfig(exposed=FlagExposed.kYes, constructor=FlagConstructor.kNew, length=0, v8_array=0, immutable=0, has_constructor=1)
construct_110021 = ConstructorConfig(exposed=FlagExposed.kYes, constructor=FlagConstructor.kNew, length=0, v8_array=0, immutable=FlagImmutable.prototype, has_constructor=1)
construct_110101 = ConstructorConfig(exposed=FlagExposed.kYes, constructor=FlagConstructor.kNew, length=0, v8_array=FlagArrayProto.iterator, immutable=0, has_constructor=1)
construct_111001 = ConstructorConfig(exposed=FlagExposed.kYes, constructor=FlagConstructor.kNew, length=1, v8_array=0, immutable=0, has_constructor=1)
construct_1113101 = ConstructorConfig(exposed=FlagExposed.kYes, constructor=FlagConstructor.kNew, length=1, v8_array=FlagArrayProto.iterator | FlagArrayProto.entries | FlagArrayProto.keys | FlagArrayProto.values | FlagArrayProto.forEach, immutable=0, has_constructor=1)
construct_112001 = ConstructorConfig(exposed=FlagExposed.kYes, constructor=FlagConstructor.kNew, length=2, v8_array=0, immutable=0, has_constructor=1)
construct_113001 = ConstructorConfig(exposed=FlagExposed.kYes, constructor=FlagConstructor.kNew, length=3, v8_array=0, immutable=0, has_constructor=1)
construct_114001 = ConstructorConfig(exposed=FlagExposed.kYes, constructor=FlagConstructor.kNew, length=4, v8_array=0, immutable=0, has_constructor=1)
